### PR TITLE
Nuxt/Bug Fixes

### LINKED ISSUE #310: [Bug] When creating a new track/Editing existing track, getting error "Cannot read property 'reciter' of undefined"
Tested on staging

Log into system as Moderator
Go to an album and click on add track against album
Fill out details
Click on save

Expected
Should have been redirected to the reciters page

Actual
Getting error in console, Cannot read property 'reciter' of undefined
User redirected to empty blank page
image

Same is happening when editing track
However after editing the track, error ocurred page is displayed instead of the blank page when creating new track as per above screenshot
image

### LINKED ISSUE #312: [Bug] Lyrics view is displaying the data as json instead of being rendered
Environment: staging

Logged in as moderator
Added a new track
Added some information to lyrics and clicked on save

Expected
Lyrics json should be rendered

Actual
json itself is being displayed
image

This is happening in any case even if we use the old format or the new format.
Also if we dont enter any text but changed to non-timestamped mode
Basically once we create this json structure, and we save, json structure is being displayed instead of being rendered

Also I had converted to non-timestamped added some text and then undo'd all of my changes, however in this case also json was sent instead of sending a null value to server and therefore lyrics are being displayed in wrong format

Also the metadata for this on the albums page is showing as there is lyrics for this track even though after converting to non-timestamped mode, no lyrics itself was added. but still metadata shows as there being lyrics available for that track

### LINKED ISSUE #316: [Bug] Album Artwork is not being displayed correctly from the audio player queue when no artwork is there
Environment: staging

Played a track which does not have artwork.

image

### PR DESCRIPTION
**Pull request by shea786**
This PR will close the below issues

Closes #310
Closes #312
Closes #316

### CODE REVIEW

File: nuxt/components/edit/EditTrackDialog.vue [hunk 1]
```diff
@@ -97,14 +97,13 @@
...
-  Component, Prop, Watch, Vue,
-} from 'nuxt-property-decorator';
+import { Component, Prop, Vue, Watch } from 'nuxt-property-decorator';
 import { clone } from '@/utils/clone';
 import { RequestOptions, TrackIncludes } from '@/api/tracks';
 import TimestampedEditor from '@/components/edit/lyrics/TimestampedEditor.vue';
 import { Documents, Format } from '@/entities/lyrics';
-import JsonV1Document = Documents.JsonV1.Document;
+import { getTrackUri } from '~/entities/track';
+  import JsonV1Document = Documents.JsonV1.Document;
```
Comment (szainmehdi) [inline nuxt/components/edit/EditTrackDialog.vue:106]: Not sure why this is indented
```suggestion
import JsonV1Document = Documents.JsonV1.Document;
```

File: nuxt/components/edit/EditTrackDialog.vue [hunk 2]
```diff
@@ -97,14 +97,13 @@
...
-import {
-  Component, Prop, Watch, Vue,
-} from 'nuxt-property-decorator';
+import { Component, Prop, Vue, Watch } from 'nuxt-property-decorator';
 import { clone } from '@/utils/clone';
 import { RequestOptions, TrackIncludes } from '@/api/tracks';
 import TimestampedEditor from '@/components/edit/lyrics/TimestampedEditor.vue';
 import { Documents, Format } from '@/entities/lyrics';
-import JsonV1Document = Documents.JsonV1.Document;
+import { getTrackUri } from '~/entities/track';
```
Comment (szainmehdi) [inline nuxt/components/edit/EditTrackDialog.vue:105]:
```suggestion
import { getTrackUri } from '@/entities/track';
```
