### PR TITLE
Bug 405 Fixed

### LINKED ISSUE #405: [bug] Can't play this track
https://nawhas.com/reciters/mir-hasan-mir/albums/2017/tracks/zameen-e-karbala-walay

Clicking the play button and nothing happens

Submitted By: Anonymous

### PR DESCRIPTION
**Pull request by shea786**
closes #405 

As we are already getting the tracks which belong to the album in a not paginated state, i thought it is better that we fetch the relevant data along with the initial request now that we are doing server side rendering for that

### CODE REVIEW

File: nuxt/pages/TrackPage.vue [hunk 1]
```diff
@@ -313,6 +297,13 @@ export default Vue.extend({
     savedTextColor(): string {
       return (this.isTrackSaved) ? '#FE5B00' : this.textColor;
     },
+    albumTracks(): Array<Track> | null | undefined {
```
Comment (szainmehdi) [inline nuxt/pages/TrackPage.vue:300]:
```suggestion
    albumTracks(): Array<Track> | null {
```

File: nuxt/pages/TrackPage.vue [hunk 2]
```diff
@@ -313,6 +297,13 @@ export default Vue.extend({
...
+      if (!this.track) {
+        return null;
+      }
+
+      return this.track.album?.tracks?.data;
```
Comment (szainmehdi) [inline nuxt/pages/TrackPage.vue:305]:
```suggestion
      return this.track.album?.tracks?.data ?? null;
```

**Review by szainmehdi — APPROVED** [review]
